username: 'admin'
password: 'Cisco.123'
prompt: '[local]CISCO_SMF_7F'
linux_prompt: 'CISCO_SMF_7F:ssi#'
system_hostname: 'CISCO_SMF_7F'
protocol: 'ssh'
ip: '128.1.125.120'
sys_hostname: 'CISCO_SMF_7F'
hostname: '128.1.125.120'
