username: 'staradmin'
password: 'cisco123~!'
prompt: '[local]TB-ASR5500-PGW'
linux_prompt: 'TB-ASR5500-PGW:ssi#'
system_hostname: 'TB-ASR5500-PGW'
protocol: 'ssh'
ip: '192.168.71.60'
sys_hostname: 'TB-ASR5500-PGW'
hostname: '192.168.71.60'
