username: 'admin'
password: 'ahslxj0213'
prompt: 'TB_7F_N9508_Core1'
linux_prompt: 'TB_7F_N9508_Core1'
system_hostname: 'TB_7F_N9508_Core1'
protocol: 'ssh'
ip: '172.20.77.251'
sys_hostname: 'TB_7F_N9508_Core1'
hostname: '172.20.77.251'
