username: 'admin'
password: 'cisco123~!'
prompt: '[local]TB-ASR5500-SGW'
linux_prompt: 'TB-ASR5500-SGW:ssi#'
system_hostname: 'TB-ASR5500-SGW'
protocol: 'ssh'
ip: '192.168.71.52'
sys_hostname: 'TB-ASR5500-SGW'
hostname: '192.168.71.52'
