username: 'admin'
password: 'Cisco.123'
prompt: '[local]TB_UPF1_7F'
linux_prompt: 'TB_UPF1_7F:ssi#'
system_hostname: 'TB_UPF1_7F'
protocol: 'ssh'
ip: '128.1.125.101'
sys_hostname: 'TB_UPF1_7F'
hostname: '128.1.125.101'
