username: 'admin'
password: 'Cisco.123'
prompt: '[local]TB_UPF2_7F'
linux_prompt: 'TB_UPF2_7F:ssi#'
system_hostname: 'TB_UPF2_7F'
protocol: 'ssh'
ip: '128.1.125.102'
sys_hostname: 'TB_UPF2_7F'
hostname: '128.1.125.102'
