username: 'admin'
password: 'Cisco.123'
prompt: '[local]TB_UPF02-03'
linux_prompt: 'TB_UPF02-03:ssi#'
system_hostname: 'TB_UP02-03'
protocol: 'ssh'
ip: '128.1.125.103'
sys_hostname: 'TB_UPF02-03'
hostname: '128.1.125.103'
