username: 'admin'
password: 'Cisco.123'
prompt: '[local]TB_UPF02-04'
linux_prompt: 'TB_UPF02-04:ssi#'
system_hostname: 'TB_UP02-04'
protocol: 'ssh'
ip: '128.1.125.104'
sys_hostname: 'TB_UPF02-04'
hostname: '128.1.125.104'
