username: 'admin'
password: 'Cisco.123'
prompt: '[local]TB_UPF02-05'
linux_prompt: 'TB_UPF02-05:ssi#'
system_hostname: 'TB_UP02-05'
protocol: 'ssh'
ip: '128.1.125.105'
sys_hostname: 'TB_UPF02-05'
hostname: '128.1.125.105'
