username: 'admin'
password: 'Cisco.123'
prompt: '[local]TB_UPF2_7'
linux_prompt: 'TB_UPF2_7:ssi#'
system_hostname: 'TB_UPF2_7'
protocol: 'ssh'
ip: '128.1.125.107'
sys_hostname: 'TB_UPF2_7'
hostname: '128.1.125.107'
