username: 'admin'
password: 'Cisco.123'
prompt: '[local]TB_UPF02-08'
linux_prompt: 'TB_UPF02-08:ssi#'
system_hostname: 'TB_UP02-08'
protocol: 'ssh'
ip: '128.1.125.108'
sys_hostname: 'TB_UPF02-08'
hostname: '128.1.125.108'
