username: 'admin'
password: 'Cisco.123'
prompt: '[local]TB_UPF02-09'
linux_prompt: 'TB_UPF02-09:ssi#'
system_hostname: 'TB_UPF02-09'
protocol: 'ssh'
ip: '128.1.125.109'
sys_hostname: 'TB_UPF02-09'
hostname: '128.1.125.109'
